apiVersion: 1

deleteDatasources:
  - name: prometheus

datasources:
- name: prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: true
  version: 1
- name: weave
  type: prometheus
  access: proxy
  url: https://cloud.weave.works/api/prom
  isDefault: false
  editable: true
  version: 1
  basicAuth: true
  basicAuthUser: weave
  basicAuthPassword: WEAVE_TOKEN
