apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |+
    apiVersion: 1

    deleteDatasources:
      - name: prometheus

    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: https://cloud.weave.works/api/prom
      isDefault: true
      editable: true
      version: 1
      basicAuth: true
      basicAuthUser: weave
      basicAuthPassword: WEAVE-TOKEN
