---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    component: grafana
spec:
  selector:
    component: grafana
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: http
    nodePort: 30843
